#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libmetalink
Version  : 0.1.3
Release  : 2
URL      : https://launchpad.net/libmetalink/trunk/libmetalink-0.1.3/+download/libmetalink-0.1.3.tar.xz
Source0  : https://launchpad.net/libmetalink/trunk/libmetalink-0.1.3/+download/libmetalink-0.1.3.tar.xz
Summary  : Metalink library
Group    : Development/Tools
License  : MIT
Requires: libmetalink-lib = %{version}-%{release}
Requires: libmetalink-license = %{version}-%{release}
BuildRequires : pkgconfig(cunit)
BuildRequires : pkgconfig(expat)

%description
Libmetalink
===========
Libmetalink is a library to read Metalink XML download description
format. It supports Metalink version 3 and Metalink version 4 (RFC
5854).

%package dev
Summary: dev components for the libmetalink package.
Group: Development
Requires: libmetalink-lib = %{version}-%{release}
Provides: libmetalink-devel = %{version}-%{release}

%description dev
dev components for the libmetalink package.


%package lib
Summary: lib components for the libmetalink package.
Group: Libraries
Requires: libmetalink-license = %{version}-%{release}

%description lib
lib components for the libmetalink package.


%package license
Summary: license components for the libmetalink package.
Group: Default

%description license
license components for the libmetalink package.


%prep
%setup -q -n libmetalink-0.1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551206839
export LDFLAGS="${LDFLAGS} -fno-lto"
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1551206839
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libmetalink
cp COPYING %{buildroot}/usr/share/package-licenses/libmetalink/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/metalink/metalink.h
/usr/include/metalink/metalink_error.h
/usr/include/metalink/metalink_parser.h
/usr/include/metalink/metalink_types.h
/usr/include/metalink/metalinkver.h
/usr/lib64/libmetalink.so
/usr/lib64/pkgconfig/libmetalink.pc
/usr/share/man/man3/metalink_checksum_t.3
/usr/share/man/man3/metalink_chunk_checksum_t.3
/usr/share/man/man3/metalink_delete.3
/usr/share/man/man3/metalink_file_t.3
/usr/share/man/man3/metalink_parse_fd.3
/usr/share/man/man3/metalink_parse_file.3
/usr/share/man/man3/metalink_parse_final.3
/usr/share/man/man3/metalink_parse_fp.3
/usr/share/man/man3/metalink_parse_memory.3
/usr/share/man/man3/metalink_parse_update.3
/usr/share/man/man3/metalink_parser_context_delete.3
/usr/share/man/man3/metalink_parser_context_new.3
/usr/share/man/man3/metalink_piece_hash_t.3
/usr/share/man/man3/metalink_resource_t.3
/usr/share/man/man3/metalink_t.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmetalink.so.3
/usr/lib64/libmetalink.so.3.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libmetalink/COPYING
